### ISSUE TITLE
Crash When Playing Hard AI

### ISSUE THREAD

**Issue by PatrickTulskie** [ReggieMon/tic-tac-toe#1]
Getting this error when the AI tries to pick a move using the hard difficulty.

```
tic-tac-toe-master/move_picker.rb:198:in `block in imperative_diags': undefined local variable or method `diag' for #<MovePicker:0x000001079729a0> (NameError)
```

**Comment by reggie** [comment]
Should be working now, I must have accidentally removed the variable while refactoring

**Comment by PatrickTulskie** [comment]
Awesome. Yeah now it works.

**Comment by reggie** [comment]
Thanks for pointing it out, glad it's working fine now.
